# Q1

In [3]:
import numpy as np
baseball = [100, 200, 230, 400, 500]
np_baseball = np.array(baseball)
print(np_baseball)
print(type(np_baseball))



[100 200 230 400 500]
<class 'numpy.ndarray'>


# Q2

In [6]:
height_inches = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
np_height_inches = np.array(height_inches)
np_height_meter = np_height_inches * 0.0254
print(np_height_meter)
print(type(np_height_meter))



[0.254 0.508 0.762 1.016 1.27  1.524 1.778 2.032 2.286 2.54 ]
<class 'numpy.ndarray'>


# Q3

In [7]:
height_in = [72, 75, 78, 80, 73, 77, 69, 74, 76, 71]
weight_lb = [180, 215, 210, 188, 195, 200, 170, 180, 190, 175]

np_height_in = np.array(height_in)
np_height_m = np_height_in * 0.0254

np_weight_lb = np.array(weight_lb)
np_weight_kg = np_weight_lb * 0.453592

bmi = np_weight_kg / (np_height_m ** 2)

print(bmi)

print(type(bmi))


[24.41211827 26.87285979 24.26766786 20.65265206 25.72686361 23.71627614
 25.10433334 23.11037639 23.12726994 24.40727556]
<class 'numpy.ndarray'>


# Q4

In [9]:
#height_in = [72, 75, 78, 80, 73, 77, 69, 74, 76, 71]
#weight_lb = [180, 215, 210, 188, 195, 200, 170, 180, 190, 175]

light = bmi < 21
print(light)
print(bmi[light])


[False False False  True False False False False False False]
[20.65265206]


# Q5

In [10]:
np.array([True, 1, 2]) + np.array([3, 4, False])


array([4, 5, 2])

In [13]:
np.array([4, 3, 0]) + np.array([0, 2, 2])


array([4, 5, 2])

# Q6

In [19]:
positions = ['GK', 'M', 'A', 'D', 'GK', 'M', 'A', 'D']
heights = [191, 184, 185, 180, 192, 178, 175, 182]

In [20]:
np_positions = np.array(positions)
np_heights = np.array(heights)

gk_heights = np_heights[np_positions == 'GK']

other_heights = np_heights[np_positions != 'GK']
print("Median height of goalkeepers:", np.median(gk_heights))
print("Median height of other players:", np.median(other_heights))


Median height of goalkeepers: 191.5
Median height of other players: 181.0
